### ISSUE TITLE
cool project!

### ISSUE THREAD

**Issue by aquynh** [DavidKorczynski/RePEconstruct#1]
this looks like a great tool, but will you add more info to README?

keep it up, cheers.

**Comment by marcurdy** [comment]
+1

**Comment by DavidKorczynski** [comment]
Thank you for the interest to both of you! I will write a thorough documentation before the end of the coming Sunday (30th October 2016).

**Comment by aquynh** [comment]
cant wait for that! i post about your tool on Twitter, and it got huge interest: https://twitter.com/capstone_engine/status/791675765200855040. 

the evidence is the number of stars you just got :-)

cheers.
